baseURL = 'https://miniblog.tiernanotoole.ie/'
languageCode = 'en-ie'
title = 'Tiernans Mini Blog'
theme = 'beautifulhugo'
enableGitInfo = true
#googleAnalytics = "XXX"
pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
  commit = "https://github.com/tiernano/miniblog.tiernanotoole.ie/tree/"
  readingTime = true
  wordCount = true
  cloudinary_url = "https://images.tiernanotoole.ie"
  selfHosted = true
  share_img = "https://images.tiernanotoole.ie/image/upload/w_200,ar_1:1,c_fill,g_auto,e_art:hokusai,f_auto,q_auto,dpr_auto//v1665612541/miniblog/IMG_1573.heic"
  image =  "https://images.tiernanotoole.ie/image/upload/w_200,ar_1:1,c_fill,g_auto,e_art:hokusai,f_auto,q_auto,dpr_auto//v1665612541/miniblog/IMG_1573.heic"
  logo =  "https://images.tiernanotoole.ie/image/upload/w_200,ar_1:1,c_fill,g_auto,e_art:hokusai,f_auto,q_auto,dpr_auto//v1665612541/miniblog/IMG_1573.heic"
 


[Author]
  name = "Tiernan OToole"
  website = "https://o2l.ie"
  email = "tiernan@o2l.ie"
  github = "tiernano"
  twitter = "tiernano"
  mastodon = "s.o2l.ie/@tiernano"
  #linkedin = "username"
  
  #stackoverflow = "users/XXXXXXX/username"
  youtube = "tiernanotoole" # or channel/channelname

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2